= SmartBank

SmartBank represents the gateway to the Acquiring Bank (the bank of the Merchant). It is in charge of delivering authorisations by calling the network card-scheme. The objective is to check the solvability of the card owner (the person doing the payment).

It is called by EasyPay beyond a certain amount through a RESTful API.

For this demo, the processing is purposely made in a very basic way: 

. below a configured amount: the authorization is accepted,
. beyond it: the authorization is refused.

== Using TomEE

It seems that TomEE integration does not work very well with NetBeans. A recommended approach is to use the TomEE maven plugin from a shell script. Its is defined and configured in pom.xml and can easyly bee used:[source,]
----
mvn tomee:run
----
which has the effect to download a customized TomEE version in the target directory and to run it with the deployed application.

== Endpoints

With TomEE the exposed port is 8082.

The base URL is http://localhost:8082/smartbank/api/ for all the following endpoints:

- */health* : get MP healthcheck information,
- */openapi* : get RestFul API documentation,
- **/smartbank/api/authors**: to retrieve the list of authorizations,
- **/smartbank/api/count**: to get the count of authorizations,
- **/smartbank/api/{id}**: to retrieve a given authorization.

== Configuration

The configuration makes use of MicroProfile configuration. There is a single configuration datasource: META-INF/microprofile-config.properties.

The following parameters are defined:

- **author.max.amount**: the maximum authorized amount. Up to this value, the authorization is delivered. Beyond this value, it is refused,
- **datasource.probe.request**: the database request used by MicroProfile HealthCheck.