openapi: 3.0.0
info:
  title: SmartBank
  description: This is a SmartBank demo for Oracle Code One 2019 
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: 1.0.0
servers:
- url: http://localhost:8082/smartbank
