kumuluzee:
  name: Oracle Code One Demo 2019
  env:
    name: oco-2019
  server:
      base-url: http://localhost:8080/easypay
      context-path: /easypay
      http:
          port: 8080
  rest-client:
    registrations:
      - class: org.sebjef.easypay.control.bank.BankAuthorClient
        url: http://localhost:8082/smartbank
        read-timeout: 5000
  datasources:
    - jndi-name: jdbc/easypay
      connection-url: jdbc:hsqldb:hsql://localhost/oco
      username: sa
      password: 
      pool:
        max-size: 5
        connection-timeout: 2000
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: false
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        jndi-name: jdbc/easypay
      
