= EasyPay

EasyPay is a payment system which concentrates and accepts payments from different Point of Sales for a given merchant.

Payment requests are received via a RESTFul API and are checked in the following way:

- Is the Point of Sale defined and active?
- Is the PAN (card number) valid?
- Does the PAN belong to a well-known card scheme?
- Is the card expired?
- Is the card black-listed?


If local checks are OK, the payment is accepted below a certain limit. Beyond this limit, an authorization request is sent to the Acquirer Bank, with a fallback mechanism in case of problem.

== Endpoints

With KumuluzEE, the application is deployed on port 8080.

The main endpoints are:

- **http://localhost:8080/easypay/health**: get MicropProfile HealtCheck informations,
- **http://localhost:8080/easypay/openapi**: description of the RestFul API, todo: how to display it nicely with Swagger UI?
- **http://localhost:8080/easypay/metrics**: get MicroProfile metrics
- **http://localhost:8080/easystore/api/pos**: retrieve all pos
- **http://localhost:8080//easystore/api/cards**: retrieve all cards,
- **http://localhost:8080//easystore/api/payments**: retrieve all payements,
- **http://localhost:8080//easystore/api/payments/count**: retrieve the count of payements.

== Configuration

The configuration makes use of MicroProfile config. 
There is currently one single source in /META-INF/microprofile-config.properties with the following content:

- **payment.author.threshold**: the local acceptance threshold. If the amount is greater than this value, an authorization must be requested from the bank,
- **payment.author.merchantId**: the merchant identifier to be presented to the bank,
- **payment.max.amount.fallback**: the local acceptance fallback if the bank cannot be reached. Below this value, if the bank is unreachable, the payment is accepted. Up to this value, it is accepted,
- **org.sebjef.easypay.control.bank.BankAuthorClient/mp-rest/url**: the URL to connect to the bank.
